version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: echo "Testing by GoTSaMa"
      - run: npm test
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: "Build docker image and push to GoTSaMa docker hub"
          command:
            cp Dockerfile.test Dockerfile
            docker build -t osamagotji/node4circleci:latest .
            docker build -t osamagotji/node4circleci:${CIRCLE_SHA1} .
            docker push osamagotji/node4circleci:latest
            docker push osamagotji/node4circleci:${CIRCLE_SHA1}
      - run: echo "Done by GoTSaMa"
